Algoritmo "semnome"
// 
//  
// Descrição   : questão 10
// Autor(a)    : Gabriel Victor Araújo Vieira
// Data atual  : 01/10/2021
Var
sexo,nome:caracter
idade:real

inicio
escreval("escreva seu sexo")
leia (sexo)
 escolha (sexo)
  caso "m"
   escreval("seu sexo é masculino")
  caso "f"
   escreval ("seu sexo é feminino")
  caso "a,b,c,d,e,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z"
   escreval ("favor escrever certo da proxima vez ")
  fimescolha
fimalgoritmo