Algoritmo "semnome"
// 
//  
// Descrição   : questão 2
// Autor(a)    : Gabriel victor Araújo Vieira
// Data atual  : 01/10/2021
Var
n1:inteiro
n2:real
n3:caracter
n4:logico
Inicio
n1<- 1
n2<- 1/2
n3<- "G'
N4<- 5=5
escreval("a varialvel n1 recebe o numero inteiro:" ,n1)
 escreval("a varialvel n2 recebe o numero real:" ,n2)
 escreval("a varialvel n3 recebe a letra:" ,n3)
 escreval("a varialvel n4 recebe a logica 5=5?:" ,n4)

Fimalgoritmo