Algoritmo "semnome"
// 
//  
// Descrição   : questão 5
// Autor(a)    : Gabriel Victor Araújo Vieira
// Data atual  : 01/10/2021
Var
n1,n2,n3:real
inicio
escreval("escreva o n1")
leia (n1)
escreval("escreva o n2")
leia (n2)
escreval("escreva o n3")
leia (n3)
se (n1>n2+n3)entao
escreval("o n1 é maior que a soma do n2 e n3")
senao (n2>n2+n3)
escreval ("o n1 é menor que a soma do n2 e n3")

fimse
Fimalgoritmo